### ISSUE TITLE
Scan duplicate device in Ios side

### ISSUE THREAD

**Issue by RingoWinbee** [pineappleoOilPrince/flutter_blue_elves#3]
Why do I always return to the duplicate device when I turn on the Bluetooth again and start scanning the device on the iOS side, even if I pass in a parameter that does not allow duplicates.
My blue_elves version is 0.1.4

**Comment by pineappleoOilPrince** [comment]
At present, this is a bug on the ios side. This is because the ble device will send two kinds of broadcasts, one is the broadcast with a small amount of information, and the other is the broadcast with complete information. Generally, the former is received first, and then the device is actively requested to send the broadcast of the latter. So in fact, you will receive two broadcasts each time, but ios will display both broadcasts after restarting Bluetooth after scanning a certain device for the first time

**Comment by pineappleoOilPrince** [comment]
I can’t find a good way to solve this problem at present, but I think this will not affect the use

**Comment by pineappleoOilPrince** [comment]
you can update to version 0.1.6,i  add some measures try to avoid.

**Comment by RingoWinbee** [comment]
thank
